---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

provisioner:
  name: chef_zero

platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
  run_list:
  - recipe[apt]
- name: centos-5.10

suites:
- name: server_with_storage
  run_list: 
    - bacula-backup::storage
    - bacula-backup::server
  attributes: 
    mysql:
      server_debian_password: test
      server_root_password: test
      server_repl_password: test
  excludes:
    - centos-5.10
- name: client
  run_list: 
    - bacula-backup::client
  attributes: {}
- name: monitor
  run_list: 
    - bacula-backup::server
    - bacula-backup::bat
  attributes: {}
  excludes:
    - centos-5.10
- name: server_with_tape_storage
  run_list: 
    - bacula-backup::storage
    - bacula-backup::server
  attributes: 
    bacula:
      dir:
        pools: [
        {
          "Name": "MyFilePool",
          "Volume Retention": "365 days",
          "Storage": "\"File\"",
          "Pool Type": "Backup",
          "RecyclePool": "Scratch",
          "Recycle Oldest Volume": "yes"
        }
      ]
      sd:
        autochangers: [
          {
            "Name": "mytapelibrary",
            "Device": "LTO5-1",
            "Changer Command": "\"/etc/bacula/scripts/mtx-changer %c %o %S %a %d\"",
            "Changer Device": "/dev/sg7"
          }
        ]
        devices: [
          {
            "Name": "LTO5-1",
            "Media Type": "LTO-5",
            "RemovableMedia": "yes",
            "RandomAccess": "no",
            "Archive Device": "/dev/nst1",
            "Maximum File Size": "5GB",
            "Autochanger": "yes",
            "AutomaticMount": "yes",
            "Alert Command": "\"sh -c 'tapeinfo -f %c |grep TapeAlert|cat'\"",
            "Maximum Spool Size": "75161927680",
            "Maximum Network Buffer Size": "65536"
          }
        ]
        dir-devices: [
          {
            "Device": "mytapelibrary",
            "Media Type": "LTO-5",
            "AllowCompression": "no",
            "Autochanger": "yes"
          }
        ]
    dev_mode: true
    mysql:
      server_debian_password: test
      server_root_password: test
      server_repl_password: test
  excludes:
    - centos-5.10
