---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
  run_list:
  - recipe[apt]

suites:
- name: server_with_storage
  run_list: 
    - bacula-backup::storage
    - bacula-backup::server
  attributes: 
    mysql:
      server_debian_password: test
      server_root_password: test
      server_repl_password: test
- name: client
  run_list: 
    - bacula-backup::client
  attributes: {}
- name: monitor
  run_list: 
    - bacula-backup::server
    - bacula-backup::bat
  attributes: {}
